### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by xe11** [BMukhtar/linear-gradient-any-angle#1]
Hello @BMukhtar!
Thanks for the great article on Medium! 👍 
Maybe, you could add some Open Source license like Apache 2.0 to your code to make it possible to re-use it?

**Comment by BMukhtar** [comment]
Hi @xe11! Added Apache 2.0 license. You are welcome. Feel free to reuse it and change it as you want

**Comment by xe11** [comment]
Thank you so much @BMukhtar :)
